---
- name: Ensure existence of Elasticsearch config directory
  file:
    path: "{{ config_dir|default(default_config_dir) }}"
    state: directory
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"
  become: true

- name: Copy jvm_options configuration in place
  template:
    src: "{{ jvm_options_config }}.j2"
    dest: "{{ config_dir|default(default_config_dir) }}/{{ jvm_options_config }}"
    owner: "{{ elasticsearch_user }}"
    group: "{{ elasticsearch_user }}"
    mode: 0644
  vars:
    options: "{{ jvm_options }}"
  become: true
  when: jvm_options is defined and jvm_options is not none
