---
- name: Create Kibana config directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
  loop:
    - "{{ config_dir }}"
  tags:
    - config

- name: Render kibana.yml configuration
  become: true
  template:
    src: "{{ _kibana_config_file }}.j2"
    dest: "{{ config_dir }}/{{ _kibana_config_file }}"
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
    mode: 0644
  vars:
    conf: "{{ config }}"
  when: config is defined and config.keys()|length > 0
  tags:
    - config

- name: Create Kibana data directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
  loop:
    - "{{ config['path.data']|default(config.path.data) }}"
  when: config['path.data'] is defined or config.path.data is defined
  tags:
    - config
    - data

- name: Create Kibana log directory
  become: true
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ kibana_user }}"
    group: "{{ kibana_user }}"
  loop:
    - "{{ config['logging.dest']|default(config.logging.dest) }}"
  when: config['logging.dest'] is defined or config.logging.dest is defined
  tags:
    - config
    - log
