---
- name: Set unit [Service] configuration
  set_fact:
    default_service_unit:
      ExecStart: "{{ install_dir }}/bin/elasticsearch {{ extra_run_args|join(' ') }}"
      User: "{{ elasticsearch_user }}"
      Group: "{{ elasticsearch_user }}"
      StandardOutput: journal
      StandardError: inherit

- name: Setup elasticsearch systemd unit
  include_role:
    name: 0x0i.systemd
  vars:
    unit_config:
      - name: elasticsearch
        Unit:
          Description: Elasticsearch
          Documentation: http://www.elastic.co
          Wants: network-online.target
          After: network-online.target
        Service: "{{ default_service_unit | combine(custom_unit_properties) }}"
        Install:
          WantedBy: multi-user.target
  when: install_type == 'archive'

- name: Ensure start of elasticsearch service
  service:
    name: elasticsearch
    state: started
    enabled: "yes"
